### ISSUE TITLE
Access Signal Parameters

### ISSUE THREAD

**Issue by hoodie** [diwic/dbus-rs-docs#1]
Hi there,
thank you very much for this crate, I'm using it for my own [notify-rust crate](https://github.com/hoodie/notify-rust/).
I would like to [implement](https://github.com/hoodie/notify-rust/blob/master/src/lib.rs#L411) a Signal listener for `ActionInvoked(UInt32,String)`.
Unfortunately I can't tell from your documentation, or examples, how to access the two parameters passed by the Signal.
Do you perhaps have a hint for me?

**Comment by diwic** [comment]
Hi,
have you tried `s.get_items()`? Where `s` is the `Message` inside `ConnectionItem::Signal()`. For your particular signal, `s.get_items()` should return a `Vec` of two items, the first being an `UInt32` and the second one being a `String`.

That said, you're right in that there is no example or test case that covers this, so probably it has not been tested. Let me know if it works or not!

**Comment by hoodie** [comment]
That worked, thank you very much, I had neglected that because it needed to be mutable to access get_items().
Thanks

**Comment by hoodie** [comment]
BTW: it seems to work if get_items() does not take a mutable self.

``` rust
    pub fn get_items(&self) -> Vec<MessageItem> {...
```

**Comment by diwic** [comment]
You're right, I'm not sure why it takes a `&mut self`. I've changed that now.

But it shouldn't be a problem that it does, either - the iterator hands out messages, not immutable references to them, so you should be able to get a `&mut self` pretty easily.

**Comment by hoodie** [comment]
true, it just made it a bit more difficult to use
